# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  pokefaces:
    image: pokefaces
    build:
      context: .
      dockerfile: PokeFaces/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 6000:6000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
